name: Deploy Python project to Azure Function App

on:
  push:
    branches: [main]

env:
  AZURE_FUNCTIONAPP_NAME: 'CodingCrazy'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'     # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.9'                   # set this to the python version to use (e.g. '3.6', '3.7', '3.8')
  RESOURCE_GROUP_NAME: 'DefaultResourceGroup-EUS' # set this to your Azure resource group name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"

    - name: 'Install Playwright and Browsers'
      run: |
        pip install playwright
        export PLAYWRIGHT_BROWSERS_PATH=/home/site/wwwroot/my-playwright-browsers
        playwright install

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Create directory for Playwright'
      run: |
        az functionapp ssh --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --command "mkdir -p /home/site/wwwroot/my-playwright-browsers"

    - name: 'Deploy Function App'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true

    - name: 'Start Azure Function App'
      run: |
        az functionapp start --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }}

    - name: 'Stream Logs from Azure Function App'
      run: |
        az functionapp log tail --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }}
